name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Python Assingment 2
      id: python-assingment-2
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 60
        setup-command: pip install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYTHON-ASSINGMENT-2_RESULTS: "${{steps.python-assingment-2.outputs.result}}"
      with:
        runners: python-assingment-2
